### ISSUE TITLE
DocumentView not scrolling

### ISSUE THREAD

**Issue by sitilge** [bluejamesbond/TextJustify-Android#60]
Using the library TextJustify-Android I am not able to make the DocumentView scrollable. The text is shown correctly, justified, however the lower part is cut of instead of making it scrollable. I tried to put the DocumentView in ScrollView but then the text was not even shown...

![screen shot 2015-01-26 at 16 56 47](https://cloud.githubusercontent.com/assets/3306642/5901594/580af70c-a57c-11e4-8914-e4487616f072.png)

**Comment by bluejamesbond** [comment]
Can you post some more code please? Your full XML and activity. 



—

**Comment by bluejamesbond** [comment]
@sitilge Remove the `maxLines` attribute

**Comment by sitilge** [comment]
@bluejamesbond Still not working... Updated SO: http://stackoverflow.com/questions/28065571/textjustify-android-not-loading-and-scrolling

**Comment by bluejamesbond** [comment]
Remove the `maxLines` attribute from the XML layout. Currently you are setting the maxLines which seems to limit the content to just 100 lines. And don't put `DocumentView` inside a `ScrollView` because `DocumentView` is actually a subclass of `ScrollView`.

As a sidenote, I recommend you check out the `SqueezeHyphenator` which will hyphenate your text inside `DocumentView`

**UPDATE**: It works fine for me. You can see my [demo](https://www.dropbox.com/s/hernb795uxf1ds3/2015_01_27_03_55_43.mp4?dl=0). I can post my demo on Github upon request.

It is possible that you are not calling `documentView.requestLayout()` after you set the text.

**Comment by viktorelo** [comment]
The link to your demo is broken, can you please fix it? I'm having the same issue as OP, but only on devices below API 14.
